const express = require("express")
const badges = require('./badges')
const meets = require('./meets')
const mentees = require('./mentees')
const mentor = require('./mentor')
const router = express.Router()
const user = require('./user')
const auth = require('./auth')
const target = require('./targets')
const note = require('./notes')

router.use('/auth',auth)
router.use('/user',user)
router.use('/target',target)
router.use('/note',note)
router.use('/badges',badges)
router.use('/meets',meets)
router.use('/mentees',mentees)
router.use('/mentor',mentor)

module.exports = router